[[plugins]] # color scheme
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
  let g:nord_cursor_line_number_background = 0
  let g:nord_uniform_diff_background = 0
'''

[[plugins]] # NERDTree
repo = 'preservim/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
  nnoremap <silent><C-a> :NERDTreeFind<CR>:vertical res 30<CR>
'''

[[plugins]] # neoterm
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_autoinsert = 1
  let g:neoterm_default_mod = 'botright'
  let g:neoterm_autoscroll = 1
  let g:neoterm_automap_keys = '<C-c>'
  nnoremap <C-n> :Tnew<CR>
  nnoremap <silent><C-t> :<c-u>exec v:count.'Topen'<CR>
  nnoremap <silent><C-l> :Tclear<CR>
  nnoremap <silent><C-h> :TcloseAll<CR>
  nnoremap td :Tclose!<CR>
  tnoremap <silent><C-w><C-w> <C-\><C-n><C-w><C-w>
  tnoremap <silent><C-h> <C-\><C-n>:TcloseAll<CR>
'''

[[plugins]] # ウィンドウの幅をctr+eで調整
repo = 'simeji/winresizer'

[[plugins]] # airline
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
  let g:airline_powerline_fonts = 0
  let g:airline_theme = 'nord'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#tabline#fnamemod = ':t'
'''

[[plugins]] # gitの各種コマンド実行
repo = 'tpope/vim-fugitive'
hook_add = '''
  :command Gs Gstatus
  :command Gd Gvdiff
'''

[[plugins]] # gitのHEADとの差分を表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # linters
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  let g:ale_linters = {
    \ 'ruby': ['rubocop', 'solargraph'],
    \ }
  let g:ale_sign_error='E'
  let g:ale_sign_warning='W'
'''

[[plugins]] # インデントの可視化
repo = 'Yggdroot/indentLine'

[[plugins]] # コメントアウト
repo = 'tpope/vim-commentary'

[[plugins]] # 括弧のレインボーハイライト
repo = 'luochen1990/rainbow'
hook_add = '''
  let g:rainbow_active = 1
'''

[[plugins]] # 括弧の補完
repo = 'jiangmiao/auto-pairs'

[[plugins]] # 括弧やタグに対するコマンド
repo = 'tpope/vim-surround'

[[plugins]] # ドットコマンドの強化
repo = 'tpope/vim-repeat'

# ------------------------------------------------------------
# syntax highlighting
# ------------------------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''
on_ft = ['json']

# ------------------------------------------------------------
# ruby
# ------------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

# ------------------------------------------------------------
# terraform
# ------------------------------------------------------------
[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
  let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'

[[plugins]] # Only for Linter
repo = 'neomake/neomake'

# ------------------------------------------------------------
# completion
# ------------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

# ------------------------------------------------------------
# fzf
# ------------------------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
  \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
  \ <bang>0)
  nnoremap <C-g> :Rg<Space>
  nnoremap <C-p> :Files<CR>
  nnoremap <C-y> :History<CR>
'''

# ------------------------------------------------------------
# vim-lsp
# ------------------------------------------------------------
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  let g:lsp_settings_servers_dir = '~/.dein/vim-lsp-settings/servers'
'''
