#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ------------------------------------------------------------ 
# Neovimの設定ファイル読み込み先
# ------------------------------------------------------------ 
export XDG_CONFIG_HOME=$HOME/dotfiles

# ------------------------------------------------------------ 
# peco
# ------------------------------------------------------------ 
function peco-history-selection() {
    BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
    zle reset-prompt
}
zle -N peco-history-selection
bindkey '^R' peco-history-selection

# ------------------------------------------------------------ 
# anyenv
# ------------------------------------------------------------ 
export PATH=$HOME/.anyenv/bin:$PATH
eval "$(anyenv init -)"

# ------------------------------------------------------------ 
# rbenv
# ------------------------------------------------------------ 
export PATH=$HOME/.rbenv/bin:$PATH
eval "$(rbenv init -)"

# ------------------------------------------------------------ 
# nodenv
# ------------------------------------------------------------ 
export PATH=$HOME/.nodenv/versions/15.5.0/bin:$PATH
eval "$(nodenv init -)" # nodenvを自動的にロードする

# ------------------------------------------------------------ 
# mysql
# ------------------------------------------------------------ 
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

# ------------------------------------------------------------ 
# fzf
# ------------------------------------------------------------ 
export PATH="$PATH:$HOME/.fzf/bin"
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'
export FZF_DEFAULT_OPTS='--height 30% --border'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ------------------------------------------------------------ 
# AWS CLI completer
# ------------------------------------------------------------ 
if [ -f /usr/local/bin/aws_zsh_completer.sh ]; then
  source /usr/local/bin/aws_zsh_completer.sh
fi

# ------------------------------------------------------------ 
# source zshlocal
# ------------------------------------------------------------ 
if [ -f ~/.zshlocal ]; then
  source ~/.zshlocal
fi

# ------------------------------------------------------------ 
# alias
# ------------------------------------------------------------ 
alias vi='nvim'
alias aws_mfa='oathtool --totp --base32 $AWS_MFA_SECRET_KEY | pbcopy ; pbpaste'
alias iam_mfa='oathtool --totp --base32 $IAM_MFA_SECRET_KEY | pbcopy ; pbpaste'

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/Cellar/tfenv/1.0.2/versions/0.12.25/terraform terraform
