#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ------------------------------------------------------------
# ターミナル起動時に画面を最大化
# ------------------------------------------------------------
printf '\e[9;1t'

# ------------------------------------------------------------
# source zshlocal
# ------------------------------------------------------------
if [ -f ~/.zshlocal ]; then
  source ~/.zshlocal
fi

# ------------------------------------------------------------
# Neovimの設定ファイル読み込み先
# ------------------------------------------------------------
export XDG_CONFIG_HOME=$HOME/dotfiles

# ------------------------------------------------------------
# peco
# ------------------------------------------------------------
function peco-history-selection() {
    BUFFER=`history -n 1 | tail -r  | awk '!a[$0]++' | peco`
    CURSOR=$#BUFFER
    zle reset-prompt
}
zle -N peco-history-selection
bindkey '^R' peco-history-selection

# ------------------------------------------------------------
# anyenv
# ------------------------------------------------------------
export PATH=$HOME/.anyenv/bin:$PATH
eval "$(anyenv init -)"

# ------------------------------------------------------------
# alias
# ------------------------------------------------------------
alias vi='nvim'
